[package]
name = "solana"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
solana-client = "1.18.0"
solana-program = "1.18.0"
solana-sdk = "1.18.0"
tokio = { version = "1.48.0", features = ["full"] }