# .cargo/config.toml
[build]
target = "x86_64-unknown-linux-gnu"  # optional, usually inferred
incremental = true


[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-fuse-ld=mold", "-C", "force-frame-pointers=yes"]
